services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localtest
      MYSQL_USER: appuser
      MYSQL_PASSWORD: wns171909
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: optional:file:/app/.env.properties
    volumes:
      - ./build/libs/app.jar:/app.jar
      - ./.env.properties:/app/.env.properties
    command: ["java", "-jar", "/app.jar", "--spring.config.import=optional:file:/app/.env.properties"]

